---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headers-unmatch
spec:
  ingressClassName: nginx
  rules:
  - host: headers.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: header-unmatch
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headers-match
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "Foo"
    # nginx.ingress.kubernetes.io/canary-by-header-value: Bar
    nginx.ingress.kubernetes.io/canary-by-header-pattern: "[Bb]ar"
spec:
  ingressClassName: nginx
  rules:
  - host: headers.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: header-match
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: header-match
spec:
  type: ClusterIP
  selector:
    app: header-match
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-match
  labels:
    app: header-match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: header-match
  template:
    metadata:
      labels:
        app: header-match
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
---
apiVersion: v1
kind: Service
metadata:
  name: header-unmatch
spec:
  type: ClusterIP
  selector:
    app: header-unmatch
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: header-unmatch
  labels:
    app: header-unmatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: header-unmatch
  template:
    metadata:
      labels:
        app: header-unmatch
    spec:
      containers:
      - name: echo
        image: mendhak/http-https-echo:latest
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"